### ISSUE TITLE
npx make-magic using hasura template

### ISSUE THREAD

**Issue by jesuslopezlugo** [magiclabs/create-magic-app#80]
### ✅ Prerequisites

- [X] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [X] Are you running the latest SDK version?
- [X] Are you reporting to the correct repository (`make-magic`)?

### 🐛 Description

When try to run `npx make-magic` and select `hasura` as template and set the public, secret, GraphQL URL, and session length  I get this error:

```js
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (fs.js:1487:5)
    at e (/Users/jesuslopezlugo/.npm/_npx/938d552738feb8b4/node_modules/make-magic/dist/compiled/zombi/index.js:1:189954)
    at Object.e.writeFile (/Users/jesuslopezlugo/.npm/_npx/938d552738feb8b4/node_modules/make-magic/dist/compiled/zombi/index.js:1:190088)
    at /Users/jesuslopezlugo/.npm/_npx/938d552738feb8b4/node_modules/make-magic/dist/compiled/zombi/index.js:1:175486
    at /Users/jesuslopezlugo/.npm/_npx/938d552738feb8b4/node_modules/make-magic/dist/compiled/zombi/index.js:1:172051
    at o (/Users/jesuslopezlugo/.npm/_npx/938d552738feb8b4/node_modules/make-magic/dist/compiled/zombi/index.js:1:196562)
    at FSReqCallback.oncomplete (fs.js:193:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### 🧩 Steps to Reproduce

1.  Execute `npx make-magic` 
2. Select `hasura` template
3. Fill the Magic publishable API key with a valid value
4. Fill the Magic secret API key with a valid value
5. Fill the Hasura GraphQL URL with a valid value
6. Fill the session length in # of day with a valid integer value
7. Select `npm` as NPM client

### 🤔 Expected behavior

Finish execution successfully and generate a scaffold magic link with hasura project

### 😮 Actual behavior

Execution fail with this error

```js
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (fs.js:1487:5)
    at e (/Users/jesuslopezlugo/.npm/_npx/938d552738feb8b4/node_modules/make-magic/dist/compiled/zombi/index.js:1:189954)
    at Object.e.writeFile (/Users/jesuslopezlugo/.npm/_npx/938d552738feb8b4/node_modules/make-magic/dist/compiled/zombi/index.js:1:190088)
    at /Users/jesuslopezlugo/.npm/_npx/938d552738feb8b4/node_modules/make-magic/dist/compiled/zombi/index.js:1:175486
    at /Users/jesuslopezlugo/.npm/_npx/938d552738feb8b4/node_modules/make-magic/dist/compiled/zombi/index.js:1:172051
    at o (/Users/jesuslopezlugo/.npm/_npx/938d552738feb8b4/node_modules/make-magic/dist/compiled/zombi/index.js:1:196562)
    at FSReqCallback.oncomplete (fs.js:193:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### 🌎 Environment

| Software            | Version(s) |
| ------------------- | ---------- |
| `make-magic`        |  v3.3.0
| Node                |  14.17.4
| npm | 8.4.1
| Operating System    | Mac OS 13.1 (Ventura)

**Comment by jamesrp13** [comment]
We've overhauled the CLI with new templates. This template is no longer supported.
